import React, { useState } from 'react';
import { useLogStore } from '../../store/useLogStore';
import { useFilteredLogs } from '../../hooks/useFilteredLogs';
import { trackExportDownloaded } from '../../lib/analytics/gtag';
import { X, Download, FileText, FileSpreadsheet, FileCode, Check } from 'lucide-react';

export const ExportModal: React.FC = () => {
  const isOpen = useLogStore((state) => state.isExportOpen);
  const setIsOpen = useLogStore((state) => state.setExportOpen);
  const logResult = useLogStore((state) => state.logResult);
  const fileInfo = useLogStore((state) => state.fileInfo);
  const { filteredEntries, filteredSlowQueries } = useFilteredLogs();

  const [downloadedFormat, setDownloadedFormat] = useState<string | null>(null);

  if (!isOpen || !logResult) return null;

  const triggerDownload = (content: string, filename: string, type: string, format: string, count: number) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    trackExportDownloaded(format, count);
    setDownloadedFormat(filename);
    setTimeout(() => setDownloadedFormat(null), 2500);
  };

  const exportFilteredJSON = () => {
    const data = JSON.stringify(filteredEntries, null, 2);
    triggerDownload(data, `${fileInfo?.name || 'mongolens'}-filtered.json`, 'application/json', 'json', filteredEntries.length);
  };

  const exportFilteredJSONL = () => {
    const data = filteredEntries.map((e) => JSON.stringify(e)).join('\n');
    triggerDownload(data, `${fileInfo?.name || 'mongolens'}-filtered.jsonl`, 'application/x-ndjson', 'jsonl', filteredEntries.length);
  };

  const exportFilteredCSV = () => {
    const headers = ['Line', 'Timestamp', 'Severity', 'Component', 'Operation', 'Namespace', 'DurationMs', 'Plan', 'DocsExamined', 'KeysExamined', 'Message'];
    const rows = filteredEntries.map((e) => [
      e.lineNumber,
      `"${e.timestamp}"`,
      `"${e.severity}"`,
      `"${e.component}"`,
      `"${e.operation || ''}"`,
      `"${e.namespace || ''}"`,
      e.durationMillis || 0,
      `"${e.planSummary || ''}"`,
      e.docsExamined || 0,
      e.keysExamined || 0,
      `"${(e.message || '').replace(/"/g, '""')}"`,
    ]);
    const csvContent = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
    triggerDownload(csvContent, `${fileInfo?.name || 'mongolens'}-logs.csv`, 'text/csv', 'csv', filteredEntries.length);
  };

  const exportSlowQueriesCSV = () => {
    const headers = ['Timestamp', 'DurationMs', 'Namespace', 'Operation', 'PlanSummary', 'DocsExamined', 'KeysExamined', 'nReturned', 'Command'];
    const rows = filteredSlowQueries.map((e) => [
      `"${e.timestamp}"`,
      e.durationMillis || 0,
      `"${e.namespace || ''}"`,
      `"${e.operation || ''}"`,
      `"${e.planSummary || ''}"`,
      e.docsExamined || 0,
      e.keysExamined || 0,
      e.nReturned || 0,
      `"${(e.commandStr || '').replace(/"/g, '""')}"`,
    ]);
    const csvContent = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
    triggerDownload(csvContent, `${fileInfo?.name || 'mongolens'}-slow-queries.csv`, 'text/csv', 'slow_queries_csv', filteredSlowQueries.length);
  };

  const exportRawTXT = () => {
    const data = filteredEntries.map((e) => e.raw).join('\n');
    triggerDownload(data, `${fileInfo?.name || 'mongolens'}-raw.txt`, 'text/plain', 'txt', filteredEntries.length);
  };

  const exportDiagnosticMarkdown = () => {
    const summary = logResult.summary;
    const md = `# MongoDB Log Diagnostic Summary Report
Generated by MongoLens • ${new Date().toUTCString()}
File: ${fileInfo?.name || 'mongod.log'}

## Key Performance Indicators
- **Total Log Entries:** ${summary.totalEntries.toLocaleString()}
- **Slow Queries (>=100ms):** ${summary.slowQueriesCount.toLocaleString()}
- **Errors Encountered:** ${summary.errorsCount.toLocaleString()}
- **Average Query Duration:** ${summary.avgDuration} ms
- **P95 Query Duration:** ${summary.p95Duration} ms
- **P99 Query Duration:** ${summary.p99Duration} ms
- **Max Latency Recorded:** ${(summary.maxDuration / 1000).toFixed(2)} s
- **Time Range:** ${summary.timeRange?.start || 'N/A'} → ${summary.timeRange?.end || 'N/A'}

---

## Top Slow Queries
${filteredSlowQueries.slice(0, 10).map((q, idx) => `
### ${idx + 1}. [${q.durationMillis}ms] ${q.operation?.toUpperCase()} on \`${q.namespace}\`
- **Timestamp:** ${q.timestamp}
- **Plan Summary:** \`${q.planSummary || 'N/A'}\`
- **Docs Examined:** ${q.docsExamined?.toLocaleString() || 0} | **Keys Examined:** ${q.keysExamined?.toLocaleString() || 0} | **Returned:** ${q.nReturned || 0}
\`\`\`json
${q.command ? JSON.stringify(q.command, null, 2) : q.commandStr || q.raw}
\`\`\`
`).join('\n')}

---

## Collections Performance
| Namespace | Total Queries | Avg Duration | P95 Duration | Slow Queries | COLLSCAN Count |
|---|---|---|---|---|---|
${logResult.collections.map((c) => `| \`${c.namespace}\` | ${c.queriesCount.toLocaleString()} | ${c.avgDuration}ms | ${c.p95Duration}ms | ${c.slowQueriesCount} | ${c.collscanCount} |`).join('\n')}

---

## Error Clusters
${logResult.errorGroups.map((g) => `- **[${g.count}x] ${g.component}:** ${g.message} (Last seen: ${g.lastSeen})`).join('\n')}
`;

    triggerDownload(md, `${fileInfo?.name || 'mongolens'}-diagnostic-report.md`, 'text/markdown', 'markdown_report', 1);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-sm animate-fade-in">
      <div
        className="w-full max-w-xl bg-[#0d1424] border border-white/15 rounded-2xl shadow-2xl overflow-hidden animate-slide-up"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="p-4 border-b border-white/10 flex items-center justify-between bg-[#090d16]">
          <div className="flex items-center gap-2.5">
            <div className="w-7 h-7 rounded-lg bg-brand-500/10 border border-brand-500/20 flex items-center justify-center text-brand-400">
              <Download className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm font-semibold text-white">Export Log Diagnostics</h3>
              <p className="text-[11px] text-slate-400">Download formatted records and diagnostic summaries</p>
            </div>
          </div>
          <button
            onClick={() => setIsOpen(false)}
            className="p-1 rounded-lg hover:bg-white/10 text-slate-400 hover:text-white transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Content */}
        <div className="p-3.5 sm:p-4 space-y-3 max-h-[75vh] overflow-y-auto">
          {/* Diagnostic Markdown Report */}
          <div className="p-3 sm:p-3.5 rounded-xl bg-brand-950/30 border border-brand-500/30 hover:border-brand-500/60 transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-2.5">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-lg bg-brand-500/20 text-brand-300 flex items-center justify-center shrink-0">
                <FileText className="w-4 h-4" />
              </div>
              <div>
                <h4 className="text-xs font-semibold text-slate-100">Diagnostic Executive Report</h4>
                <p className="text-[11px] text-slate-400">Comprehensive Markdown report with KPIs & slow queries</p>
              </div>
            </div>
            <button
              onClick={exportDiagnosticMarkdown}
              className="px-3 py-1.5 rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-semibold transition-colors flex items-center gap-1.5 shadow-sm self-end sm:self-auto"
            >
              <Download className="w-3.5 h-3.5" />
              Markdown
            </button>
          </div>

          {/* Slow Queries CSV */}
          <div className="p-3 sm:p-3.5 rounded-xl bg-slate-900/90 border border-white/10 hover:border-white/20 transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-2.5">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-lg bg-orange-500/15 text-orange-400 flex items-center justify-center shrink-0">
                <FileSpreadsheet className="w-4 h-4" />
              </div>
              <div>
                <h4 className="text-xs font-semibold text-slate-100">Slow Queries Dataset</h4>
                <p className="text-[11px] text-slate-400">{filteredSlowQueries.length.toLocaleString()} slow queries in CSV format</p>
              </div>
            </div>
            <button
              onClick={exportSlowQueriesCSV}
              className="px-3 py-1.5 rounded-lg bg-white/10 hover:bg-white/15 text-slate-200 text-xs font-medium transition-colors flex items-center gap-1.5 border border-white/10 self-end sm:self-auto"
            >
              <Download className="w-3.5 h-3.5 text-orange-400" />
              CSV
            </button>
          </div>

          {/* Full Filtered Logs JSON / JSONL */}
          <div className="p-3 sm:p-3.5 rounded-xl bg-slate-900/90 border border-white/10 hover:border-white/20 transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-2.5">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-lg bg-cyan-500/15 text-cyan-400 flex items-center justify-center shrink-0">
                <FileCode className="w-4 h-4" />
              </div>
              <div>
                <h4 className="text-xs font-semibold text-slate-100">Filtered Normalized Logs</h4>
                <p className="text-[11px] text-slate-400">{filteredEntries.length.toLocaleString()} matching log entries</p>
              </div>
            </div>
            <div className="flex gap-2 self-end sm:self-auto">
              <button
                onClick={exportFilteredJSON}
                className="px-2.5 py-1.5 rounded-lg bg-white/10 hover:bg-white/15 text-slate-200 text-xs font-medium transition-colors border border-white/10"
              >
                JSON
              </button>
              <button
                onClick={exportFilteredJSONL}
                className="px-2.5 py-1.5 rounded-lg bg-white/10 hover:bg-white/15 text-slate-200 text-xs font-medium transition-colors border border-white/10"
              >
                JSONL
              </button>
            </div>
          </div>

          {/* CSV & Raw TXT */}
          <div className="p-3 sm:p-3.5 rounded-xl bg-slate-900/90 border border-white/10 hover:border-white/20 transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-2.5">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-lg bg-purple-500/15 text-purple-400 flex items-center justify-center shrink-0">
                <FileText className="w-4 h-4" />
              </div>
              <div>
                <h4 className="text-xs font-semibold text-slate-100">All Log Fields / Raw Log Text</h4>
                <p className="text-[11px] text-slate-400">Export table fields or unparsed original log lines</p>
              </div>
            </div>
            <div className="flex gap-2 self-end sm:self-auto">
              <button
                onClick={exportFilteredCSV}
                className="px-2.5 py-1.5 rounded-lg bg-white/10 hover:bg-white/15 text-slate-200 text-xs font-medium transition-colors border border-white/10"
              >
                CSV
              </button>
              <button
                onClick={exportRawTXT}
                className="px-2.5 py-1.5 rounded-lg bg-white/10 hover:bg-white/15 text-slate-200 text-xs font-medium transition-colors border border-white/10"
              >
                TXT
              </button>
            </div>
          </div>
        </div>

        {/* Status indicator if downloaded */}
        {downloadedFormat && (
          <div className="px-4 py-2 bg-emerald-950/80 border-t border-emerald-500/30 text-emerald-300 text-xs flex items-center gap-2">
            <Check className="w-4 h-4 text-emerald-400" />
            <span>Downloaded <strong>{downloadedFormat}</strong> successfully.</span>
          </div>
        )}
      </div>
    </div>
  );
};
