import type { WorkerParseResult, LogEntry } from '../../types';

export interface RCAResult {
  markdown: string;
  slack: string;
}

function formatCommand(queryItem: LogEntry): string {
  if (queryItem.commandStr) {
    try {
      return JSON.stringify(JSON.parse(queryItem.commandStr), null, 2);
    } catch {
      return queryItem.commandStr;
    }
  }
  if (queryItem.command) {
    try {
      return JSON.stringify(queryItem.command, null, 2);
    } catch {
      return String(queryItem.command);
    }
  }
  return queryItem.raw || '';
}

export function generateIncidentRCA(result: WorkerParseResult, filename: string): RCAResult {
  const { summary, slowQueries, collections, errorGroups } = result;

  // 1. Identify Top Culprits (slowest / most frequent unindexed queries)
  const collscanQueries = slowQueries.filter((q) => q.planSummary?.includes('COLLSCAN'));
  const topSlowQueries = [...slowQueries]
    .sort((a, b) => (b.durationMillis || 0) - (a.durationMillis || 0))
    .slice(0, 3);

  // 2. Worst affected collections
  const topDegradedCollections = [...collections]
    .sort((a, b) => (b.collscanCount * 1000 + b.slowQueriesCount) - (a.collscanCount * 1000 + a.slowQueriesCount))
    .slice(0, 3);

  // 3. Recommended Remediation Actions
  const actionItems: string[] = [];
  const indexSuggestions = new Set<string>();

  for (const q of topSlowQueries) {
    if (q.collection && q.command) {
      const coll = q.collection;
      const filter = q.command.filter || q.command.query || (q.command.pipeline && q.command.pipeline[0] ? q.command.pipeline[0].$match : null);
      if (filter && typeof filter === 'object') {
        const keys = Object.keys(filter).filter((k) => !k.startsWith('$'));
        if (keys.length > 0) {
          const idxSpec = keys.map((k) => `${k}: 1`).join(', ');
          indexSuggestions.add(`db.${coll}.createIndex({ ${idxSpec} }, { background: true })`);
        }
      }
    }
  }

  indexSuggestions.forEach((idxCmd) => {
    actionItems.push(`Create missing index to eliminate COLLSCAN: \`${idxCmd}\``);
  });

  if (collscanQueries.length > 0) {
    actionItems.push(`Audit ${collscanQueries.length.toLocaleString()} total collection scans detected across cluster.`);
  }

  if (summary.maxDuration > 10000) {
    actionItems.push(`Review client timeout settings: peak operation duration reached ${(summary.maxDuration / 1000).toFixed(1)}s.`);
  }

  if (errorGroups.length > 0) {
    actionItems.push(`Address ${errorGroups.length} recurring database error cluster(s), notably: ${errorGroups[0].message.slice(0, 80)}...`);
  }

  const generatedAt = new Date().toUTCString();

  const worstOffendersMarkdown = topSlowQueries.map((q, i) => {
    const docsEx = q.docsExamined != null ? q.docsExamined.toLocaleString() : '0';
    const docsRet = q.nReturned != null ? q.nReturned.toLocaleString() : '0';
    const ratio = q.docsExamined && q.nReturned ? (q.docsExamined / q.nReturned).toFixed(1) + ':1' : 'N/A';
    return `
#### ${i + 1}. [${q.durationMillis}ms] \`${q.operation?.toUpperCase() || 'OP'}\` on \`${q.namespace || 'Unknown'}\`
- **Plan:** \`${q.planSummary || 'COLLSCAN'}\`
- **Docs Examined:** ${docsEx} vs **Docs Returned:** ${docsRet} (Ratio: ${ratio})
- **Client App:** \`${q.appName || 'Unknown'}\` | **Remote:** \`${q.remote || 'Local'}\`
\`\`\`json
${formatCommand(q)}
\`\`\`
`;
  }).join('\n');

  // Markdown format (for Jira / GitHub / Notion / Post-Mortems)
  const markdown = `# 🚨 MongoDB Incident Root Cause Analysis (RCA)
**Generated by MongoLens** • ${generatedAt}  
**Source Log File:** \`${filename}\`  
**Observed Time Window:** ${summary.timeRange?.start || 'N/A'} → ${summary.timeRange?.end || 'N/A'}

---

## 1. Executive Summary
During the analyzed timeframe, the MongoDB instance processed **${summary.totalEntries.toLocaleString()} operations**. 
Performance analysis indicates **${summary.slowQueriesCount.toLocaleString()} slow queries** and **${summary.errorsCount.toLocaleString()} database errors**, resulting in severe tail-latency spikes with **P95 at ${summary.p95Duration}ms**, **P99 at ${summary.p99Duration}ms**, and a maximum recorded latency of **${(summary.maxDuration / 1000).toFixed(2)}s**.

### Key Incident Metrics
| Metric | Value | Severity |
| :--- | :--- | :--- |
| **Total Operations** | ${summary.totalOperations.toLocaleString()} | Info |
| **Slow Queries (>=100ms)** | ${summary.slowQueriesCount.toLocaleString()} | ${summary.slowQueriesCount > 50 ? '🔴 High' : '🟡 Medium'} |
| **Collection Scans (COLLSCAN)** | ${collscanQueries.length.toLocaleString()} | ${collscanQueries.length > 0 ? '🔴 Critical' : '🟢 None'} |
| **P95 Latency** | ${summary.p95Duration} ms | ${summary.p95Duration > 500 ? '🔴 High' : '🟢 Normal'} |
| **P99 Latency** | ${summary.p99Duration} ms | ${summary.p99Duration > 1000 ? '🔴 Severe' : '🟡 Elevated'} |
| **Max Peak Latency** | ${(summary.maxDuration / 1000).toFixed(2)} s | ${summary.maxDuration > 5000 ? '🔴 Outage Risk' : '🟡 High'} |
| **Database Errors** | ${summary.errorsCount.toLocaleString()} | ${summary.errorsCount > 0 ? '🔴 Attention' : '🟢 Clean'} |

---

## 2. Primary Bottlenecks & Culprits

### Top Degraded Collections
${topDegradedCollections.map((c, i) => `${i + 1}. **\`${c.namespace}\`**: ${c.queriesCount.toLocaleString()} queries | **${c.collscanCount} COLLSCANs** | P95: ${c.p95Duration}ms | Max: ${c.maxDuration}ms`).join('\n')}

### Worst Latency Offenders
${worstOffendersMarkdown}

---

## 3. Recommended Remediation Plan
${actionItems.map((a, i) => `${i + 1}. ${a}`).join('\n')}
`;

  // Slack / Teams format
  const slack = `🚨 *MongoDB Incident RCA Report — ${filename}*
*Window:* ${summary.timeRange?.start || 'N/A'} → ${summary.timeRange?.end || 'N/A'}
*Status:* ${summary.slowQueriesCount > 100 ? '🔴 CRITICAL DEGRADATION' : '🟡 PERFORMANCE SPIKE'}

*Key Metrics:*
• *Total Queries Analyzed:* ${summary.totalEntries.toLocaleString()}
• *Slow Queries:* ${summary.slowQueriesCount.toLocaleString()} (${collscanQueries.length} COLLSCANs)
• *Tail Latency:* p95 = ${summary.p95Duration}ms | p99 = ${summary.p99Duration}ms | Max = ${(summary.maxDuration / 1000).toFixed(2)}s
• *Errors:* ${summary.errorsCount.toLocaleString()}

*Top Degraded Collections:*
${topDegradedCollections.map((c) => `• \`${c.namespace}\`: ${c.collscanCount} COLLSCANs, p95: ${c.p95Duration}ms`).join('\n')}

*Immediate Action Items:*
${actionItems.slice(0, 4).map((a) => `• ${a}`).join('\n')}

_Generated with MongoLens_`;

  return { markdown, slack };
}
